---
# defaults file for kibana

server_port: 5601
server_host: 0.0.0.0
server_name: hbfdemo-kibana
elasticsearch_host: http://localhost:9200

xpack_security_encryptionKey: mynameisanthonygonsalvesmainduniyameinakelahoo