---
# tasks file for mysql

 - name: Install mysql with apt
   apt:
    name: mysql-server
    update_cache: yes

  - name: start mysql-server
    service: 
     name: mysql
     state: started
     enabled: yes
    
...
