# Module: apache
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.5/metricbeat-module-apache.html

- module: apache
  #metricsets:
  #  - status
  period: {{ metric_status_period }}
  hosts: ["http://{{ web_server_1 }}", "http://{{ web_server_2 }}"]
  #username: "user"
  #password: "secret"
