# Variables file 

# Elasticsearch host private IP address
elastic_host: 192.168.29.2
elastic_port: 9200

# Kibana host private IP address
kibana_host: 192.168.29.2
kibana_port: 5601

# Web Server private IP address information for metricbeat apache module
web_server_1: 192.168.29.3
web_server_2: 192.168.29.232

# Toggle this to false to avoid running inital password setup after the first install
inital_password_setup: true

#Protocol for elasticsearch, additional configuration is required before https can be used
elastic_protocol: http


### Built-in User credentials < need to be moved to ansible vault >###

# Bootstrap credetials
es_api_basic_auth_username: elastic
es_api_basic_auth_password: s3cr3t

# A built-in superuser.
elastic_username: elastic
elastic_password: goodwitch
 
# The user Kibana uses to connect and communicate with Elasticsearch.
kibana_username: kibana
kibana_password: badsanta

# The user Logstash uses when storing monitoring information in Elasticsearch.
logstash_system_username: logstash_system
logstash_system_password: dragonprince

# The user the Beats use when storing monitoring information in Elasticsearch.
beats_system_username: beats_system
beats_system_password: avatar

# The user the APM server uses when storing monitoring information in Elasticsearch.
apm_system_username: apm_system
apm_system_password: mashaandthebear

# The user Metricbeat uses when collecting and storing monitoring information in Elasticsearch. It has the remote_monitoring_agent and remote_monitoring_collector built-in roles.
remote_monitoring_user_username: remote_monitoring_user
remote_monitoring_user_password: gossipgirl




