 - hosts: elk
   become: yes   
   tasks:
      
   - name: Add http.yml configurations
     template:
      src: ../roles/heartbeat/templates/http.yml
      dest: /etc/heartbeat/monitors.d/http.yml


   - name: Add tcp.yml configurations
     template:
      src: ../roles/heartbeat/templates/tcp.yml
      dest: /etc/heartbeat/monitors.d/tcp.yml


   - name: Add icmp.yml configurations
     template:
      src: ../roles/heartbeat/templates/icmp.yml
      dest: /etc/heartbeat/monitors.d/icmp.yml

