---

# This playbook deploys web servers 

- hosts: webservers
  become: yes
  vars_files:
   - ../vars/main.yml    
  
  roles:
  - ../roles/add-elastic-repo
  - ../roles/webserver
  - ../roles/metricbeat
  - ../roles/auditbeat
  - ../roles/filebeat
  - ../roles/packetbeat
  - ../roles/config-beats-apache
 


