---
# tasks file for kibana

# Installing Kibana
#

# Install Kibana 

- name: Install Kibana with apt
  apt:
   name: kibana
   update_cache: yes
 
# Configurations

   
# Replace the default elasticsearch.yml file with updated file

- name: Replace default kibana.yml configurations
  template:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml


# Starting Kibana

- name: Starting Kibana
  service:
   name: kibana
   state: started
   enabled: yes
   